name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: cr.ethanvogelsang.com
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: cr.ethanvogelsang.com/url-shortener:latest
